_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
architecture:
    value: MLP
batch_size:
    value: 1000
dataset:
    value: Jane street market data
epoch:
    value: 50
hidden_dim:
    value: 32
input_dim:
    value: 81
learning_rate:
    value: 0.5
lr:
    value: 0.5
